// asset_id: "BTC"
// data_end: "2022-04-01"
// data_orderbook_end: "2020-08-05T14:38:38.3413202Z"
// data_orderbook_start: "2014-02-24T17:43:05.0000000Z"
// data_quote_end: "2022-04-01T15:38:43.4426087Z"
// data_quote_start: "2014-02-24T17:43:05.0000000Z"
// data_start: "2010-07-17"
// data_symbols_count: 84300
// data_trade_end: "2022-04-01T15:38:50.8330000Z"
// data_trade_start: "2010-07-17T23:09:17.0000000Z"
// id_icon: "4caf2b16-a017-4e26-a348-2cea69c34cba"
// name: "Bitcoin"
// price_usd: 46595.207144581065
// type_is_crypto: 1
// volume_1day_usd: 90489393665557
// volume_1hrs_usd: 6684954554272.98
// volume_1mth_usd: 2856633943731126

export let assets = [
    {id: 'BTC', name: 'Bitcoin'},
    {id: 'NIS', name: 'NIS'},
    {id: 'LTC', name: 'Litecoin'},
    {id: 'VEN', name: 'VeChain (pre-swap)'},
    {id: 'XRP', name: 'Ripple'},
    {id: 'NMC', name: 'Namecoin'},
    {id: 'USDT', name: 'Tether'},
    {id: 'BLC', name: 'Blakecoin'},
    {id: 'DOGE', name: 'DogeCoin'},
    {id: 'NVC', name: 'Novacoin'},
    {id: 'FTC', name: 'Feathercoin'},
    {id: 'PPC', name: 'Peercoin'},
    {id: 'TRC', name: 'Terracoin'},
    {id: 'DRK', name: 'Darkcoin'},
    {id: 'ORO', name: 'ORO'},
    {id: 'TOR', name: 'Torcoin'},
    {id: 'KST', name: 'StarCoin'},
    {id: 'BTS', name: 'BitShares'},
    {id: 'NXT', name: 'Nxt'},
    {id: 'DARK', name: 'DARK'},
    {id: 'U', name: 'UCoin'},
    {id: 'ARI', name: 'Aricoin'},
    {id: 'MUE', name: 'MonetaryUnit'},
    {id: 'SONG', name: 'SongCoin'},
    {id: 'CON', name: 'PayCon'},
    {id: 'NAV', name: 'NAVCoin'},
    {id: 'MCC', name: 'MCC'},
    {id: 'RICE', name: 'RICE'},
    {id: 'GEO', name: 'GeoCoin'},
    {id: 'NTC', name: 'Natcoin'},
    {id: 'BITSD', name: 'BitSend'},
    {id: 'RED', name: 'RedCoin'},
    {id: 'ETCO', name: 'ETCO'},
    {id: 'AMBER', name: 'AmberCoin'},
    {id: 'MTLMC', name: 'Metal Music Coin'},
    {id: 'GUN', name: 'Guncoin'},
    {id: 'TIT', name: 'Titcoin'},
    {id: 'SBC', name: 'StrikeBitClub'},
    {id: 'MCL', name: 'MCL'},
    {id: 'CRAVE', name: 'Crave'},
    {id: 'FONZ', name: 'Fonziecoin'},
    {id: 'SQL', name: 'SQL'},
    {id: 'DUCK', name: 'DUCK'},
    {id: 'UNIC', name: 'UniCoin'},
    {id: 'OZC', name: 'OZC'},
    {id: 'LUX', name: 'LUXCoin'},
    {id: 'AIB', name: 'Advanced Internet Blocks'},
    {id: 'ACP', name: 'AnarchistsPrime'},
    {id: 'BTX', name: 'Bitcore'},
    {id: 'DRZ', name: 'Droidz'},
    {id: 'BSTY', name: 'GlobalBoost-Y'},
    {id: 'PXC', name: 'Phoenixcoin'},
    {id: 'LOG', name: 'Woodcoin'},
    {id: 'CRW', name: 'Crown'},
    {id: 'CESC', name: 'CryptoEscudo'},
    {id: 'SKC', name: 'Skeincoin'},
    {id: 'ORB', name: 'Orbitcoin'},
    {id: 'LTS', name: 'LTS'},
    {id: 'MARS', name: 'Marscoin'},
    {id: 'UNO', name: 'Unobtanium'},
    {id: 'BURST', name: 'Burst'},
    {id: 'XVG', name: 'Verge'},
    {id: 'DGB', name: 'DigiByte'},
    {id: 'FUNK', name: 'The Cypherfunks'},
    {id: 'PND', name: 'Pandacoin'},
    {id: 'XMG', name: 'Magi'},
    {id: 'CCB', name: 'CCB'},
    {id: 'SAK', name: 'Sharkcoin'},
    {id: 'AC', name: 'AsiaCoin'},
    {id: '8BIT', name: '8Bit'},
    {id: 'TES', name: 'TeslaCoin'},
    {id: 'XFC', name: 'XFC'},
    {id: 'ANI', name: 'Animecoin'},
    {id: 'DUO', name: 'ParallelCoin'},
    {id: 'PLC', name: 'PlusCoin'},
    {id: 'SHA', name: 'SHACoin'},
    {id: 'GRW', name: 'GRW'},
    {id: 'SJW', name: 'SJWCoin'},
    {id: '$PAC', name: 'PACcoin'},
    {id: 'LEA', name: 'LeaCoin'},
    {id: 'MOTO', name: 'Motocoin'},
    {id: 'FJC', name: 'FujiCoin'},
    {id: 'FLN', name: 'FLN'},
    {id: 'UNC', name: 'UNCoin'},
    {id: 'ADC', name: 'AudioCoin'},
    {id: 'BNX', name: 'BnrtxCoin'},
    {id: 'V', name: 'Version'},
    {id: 'POLY', name: 'Polymath'},
    {id: 'HYP', name: 'HyperStake'},
    {id: 'TTC', name: 'TittieCoin'},
    {id: 'PIGGY', name: 'New Piggycoin'},
    {id: 'QRK', name: 'Quark'},
    {id: 'VGC', name: 'VegasCoin'},
    {id: 'ELC', name: 'Elacoin'},
    {id: 'IEC', name: 'IvugeoCoin'},
    {id: 'SPT', name: 'Spots'},
    {id: 'CFC', name: 'CoffeeCoin'},
    {id: 'TEK', name: 'TEKcoin'},
    {id: 'WDC', name: 'Worldcoin'},
    {id: 'TRK', name: 'Truckcoin'},
    {id: 'ETH', name: 'Etherum'}]